### ISSUE TITLE
Missing support for armv7 and arm64 on the Docker image

### ISSUE THREAD

**Issue by acolombier** [aureq/cert-manager-webhook-ovh#13]
The Docker image published at `ghcr.io/aureq/cert-manager-webhook-ovh`  is missing support of `armv7` and `arm64` which prevents to run on light device such as RaspberryPi.

Worth to mention that the original @baarde's image had support for both these platform.

**Comment by acolombier** [comment]
I'm have prepared a PR to address this in the Github action.

**Comment by aureq** [comment]
@acolombier Do you mind trying the latest alpha version on your RPi please?

**Comment by acolombier** [comment]
Just gave it a go and works like a charm! Thanks for the quick merge.
