### ISSUE TITLE
Webhook problem

### ISSUE THREAD

**Issue by Mathie01** [aureq/cert-manager-webhook-ovh#18]
Hello !

Thank you for this work!
I installed it as a subchart on my project.

I have some issues:

1) My challenge ressource have this error :   `Warning  PresentError  12s (x6 over 2m37s)  cert-manager-challenges  Error presenting challenge: an error on the server ("Internal Server Error: \"/apis/acme.myProjectTestWW.io/v1alpha1/ovh\": Unauthorized") has prevented the request from succeeding (post ovh.acme.myProjectTestWW.io)`

My challenge pod logs : 

```
E0310 17:32:22.180059       1 webhook.go:223] Failed to make webhook authorizer request: Unauthorized
E0310 17:32:22.180106       1 errors.go:77] Unauthorized
E0310 17:32:22.220148       1 webhook.go:223] Failed to make webhook authorizer request: Unauthorized
E0310 17:32:22.220193       1 errors.go:77] Unauthorized
E0310 17:32:22.230365       1 webhook.go:223] Failed to make webhook authorizer request: Unauthorized
E0310 17:32:22.230398       1 errors.go:77] Unauthorized
E0310 17:32:25.941026       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta2.PriorityLevelConfiguration: the server has asked for the client to provide credentials (get prioritylevelconfigurations.flowcontrol.apiserver.k8s.io)
W0310 17:32:26.982142       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta2.PriorityLevelConfiguration: Unauthorized
E0310 17:32:26.982176       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta2.PriorityLevelConfiguration: failed to list *v1beta2.PriorityLevelConfiguration: Unauthorized
W0310 17:32:30.018694       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta2.PriorityLevelConfiguration: Unauthorized
E0310 17:32:30.018748       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta2.PriorityLevelConfiguration: failed to list *v1beta2.PriorityLevelConfiguration: Unauthorized
W0310 17:32:33.534894       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta2.PriorityLevelConfiguration: Unauthorized
E0310 17:32:33.534926       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta2.PriorityLevelConfiguration: failed to list *v1beta2.PriorityLevelConfiguration: Unauthorized
```

2) I have 2 pods cert-manager-webhook-ovh: one in the default namespace, and one in the cert-manager namespace. The one in default is taken into account. Is this normal?

My values.yaml : 

```
cert-manager-webhook-ovh:
  enabled: true
  groupName: acme.myProjectTestWW.io
  certManager:
    namespace: cert-manager
    serviceAccountName: myProjectTestWW-cert-manager
  issuers:
    - name: letsencrypt-prod
      create: true
      namespace: default
      kind: ClusterIssuer
      cnameStrategy: None
      acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
      email: "myMail"
      ovhEndpointName: ovh-eu
      ovhAuthenticationRef:
        applicationKeyRef:
          name: ovh-credentials
          key: applicationKey
        applicationSecretRef:
          name: ovh-credentials
          key: applicationSecret
        consumerKeyRef:
          name: ovh-credentials
          key: consumerKey
    - name: letsencrypt-staging
      create: true
      namespace: default
      kind: ClusterIssuer
      cnameStrategy: None
      acmeServerUrl: https://acme-staging-v02.api.letsencrypt.org/directory
      email: "myMail"
      ovhEndpointName: ovh-eu
      ovhAuthenticationRef:
        applicationKeyRef:
          name: ovh-credentials
          key: applicationKey
        applicationSecretRef:
          name: ovh-credentials
          key: applicationSecret
        consumerKeyRef:
          name: ovh-credentials
          key: consumerKey
```

Thank you!

**Comment by aureq** [comment]
Hi @Mathie01

I'm not sure what happening here since the referenced files aren't directly related to this webhook.

That said and since you're using a `secretRef`

- Are you sure your secret `ovh-credentials` is in the `default` namespace?
- Are you sure the secret contains the following 3 keys `applicationKey`, `applicationSecret` and `consumerKey`?
- Are you sure your OVH credentials (the values for the 3 keys) are correct and valid?
- Are you sure that each key in your secret is `base64` encoded?

If you're getting started with this webhook, may I suggest you to use `ovhAuthentication` instead of `ovhAuthenticationRef`?

**Comment by Mathie01** [comment]
Hi @aureq !

Thanks for your response

1) Yes
2) Yes, my secret :

```
apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: default
stringData:
  applicationKey: "..."
  applicationSecret: "..."
  consumerKey: "...."
```

3) Yes, I can use the API with these credentials

4) No. Because I use a tool to encrypt my secrets so I can push them to a git repository: https://github.com/bitnami-labs/sealed-secrets

I can't use ovhAuthenticationRef because I am in GitOps

**Comment by aureq** [comment]
So on 4, this is uncharted territory. I never user sealed-secrets and I don't know if any side effects.

Here are my recommendations

- use `ovhAuthentication` and not `ovhAuthenticationRef`
- don't use sealed-secrets

This should help you narrow down the issue.

**Comment by aureq** [comment]
I'd recommend reading #17 and #19 as your `serviceAccountName: myProjectTestWW-cert-manager` likely uses an incorrect value.
