### ISSUE TITLE
Update DNS record for load balancer service type

### ISSUE THREAD

**Issue by acermez** [aureq/cert-manager-webhook-ovh#24]
### What would you like?

Thank you for the awesome work! the current code is working great with cert-manager and I would like to propose a new feature since this code is already accessing the OVH DNS records, why not add a trigger/option to monitor services with load balancer type and create a DNS record with the cloud load balancer external IP address. I'm suggesting this as at the time of writing this, OVH doesn't support fixed IP address for a cloud kubernetes load balancer (and there is no annotations options as well...)
Thank you!

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
Hi @acermez 

Thank you for the suggestion.

I think what you are saying makes sense in a boarder Kubernetes context. However, this cert-manager webhook is only a webhook for cert-manager rather than a "do-it-all" kind of tool. 

Thanks
