### ISSUE TITLE
SemVer chart version

### ISSUE THREAD

**Issue by fredgate** [aureq/cert-manager-webhook-ovh#28]
### What would you like?

The chart version is of the form `vx.x.x`. It does not respect the [prerequisite for chart version specified by Helm](https://helm.sh/docs/topics/charts/#charts-and-versioning) that should follow the SemVer 2 standard.  
And that causes issues with tools like flux cd and argo cd.

Could we remove the leading `v` in the chart version ?

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by TartanLeGrand** [comment]
Let's use: https://github.com/googleapis/release-please :smile:

**Comment by aureq** [comment]
@fredgate yes, I think that should be doable. Let me see what I can do here.

**Comment by aureq** [comment]
@fredgate do you mind looking at `0.5.0-alpha.2` please? That should be what you are looking for. Please report here if you see any issues.

**Comment by fredgate** [comment]
Yes I think that is perfect :-)

**Comment by aureq** [comment]
Sweet. I'll go ahead and close that issue. `0.5.0` is out. Enjoy.
