### ISSUE TITLE
Add renovate bot

### ISSUE THREAD

**Issue by TartanLeGrand** [aureq/cert-manager-webhook-ovh#3]
Add renovate bot for the upgrade of this project. 😄 

Ref: https://github.com/renovatebot/github-action

**Comment by aureq** [comment]
Do you have an example of what renovatebot output looks like for a Go based project?
What are the advantages over dependabot?

**Comment by TartanLeGrand** [comment]
Renovate can:
- Update golang modules => https://docs.renovatebot.com/golang/
- Update Docker => https://docs.renovatebot.com/docker/
- Update Helm => https://docs.renovatebot.com/modules/manager/helm-values/

We can have more control over our configuration, PRs are cool to manage, linked to PR testing we can reduce the risk of updates. 

It can aggregate several updates in one PR and that's cool to save time.

It's free instead of dependanbot, it's cool for free opensource. 😄
