### ISSUE TITLE
Stuck in ovhDNSProviderSolver.secret

### ISSUE THREAD

**Issue by eqinox76** [aureq/cert-manager-webhook-ovh#36]
### What happened?

We have the `cert-manager-webhook-ovh` running for ~4 month now. The first challenges worked fine but now the applications seems to be stuck while authorizing against the ovh cloud.

### Expected Behavior

Normal challenge processing or a error message.
I think a timeout at https://github.com/aureq/cert-manager-webhook-ovh/blob/9a29b1252fa8c7c31c2af33cf9f2df72db578143/main.go#L156C1-L159C3 would be helpful to pinpoint the issue better.

### Steps to reproduce

Setup cert-manager and cert-manager-webhook-ovh. Create a new Certificaterequest. 

### Versions in use

ghcr.io/aureq/cert-manager-webhook-ovh:0.5.0

### Additional context

Log:
```
I1215 12:39:33.738246       1 main.go:120] "cert-manager: Starting challenge request..."                                 
I1215 12:39:33.738315       1 main.go:126] "cert-manager: Resource namespace: cert-manager"                              
I1215 12:39:33.738339       1 main.go:96] "cert-manager: Validating provider config..."                                  
I1215 12:39:34.354244       1 trace.go:236] Trace[1724277385]: "Create" accept:application/json, */*,audit-id:19617...,client:10.42.0.108,protocol:HTTP/2.0,resource:ovh,scope:resource,url:/apis/company/v1alpha1/ovh,user-agent:cert-manager-challenges/v1.12.4 (linux/amd64) cert-manager/fe41951...8,verb:POST (15-Dec-2023 12:39:33.737) (total time: 616ms):                                                                       
Trace[1724277385]: ---"Write to database call succeeded" len:546 615ms (12:39:34.354)                                    
Trace[1724277385]: [616.191806ms] [616.191806ms] END                                                                     
```

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
A few things here...
1. Could you please run the latest version of this webhook please?
2. Without your [`values.yaml`](https://github.com/aureq/cert-manager-webhook-ovh/blob/0.5.2/charts/cert-manager-webhook-ovh/values.yaml) (please use the reference and redact any secrets) it's not going to be possible to diagnose any issue.
3. Pleas indicate your cert-manager version as well as your k8s version/flavors

Thanks

**Comment by eqinox76** [comment]
Thanks for the fast response. After some more digging it turns out that i got confused by our dns setup and was asking the wrong dns server for the _acme-challenge txt entry. Therefore was assuming that the `cert-manager-webhook-ovh` failed to set the record.
But the wrong dns setup was also preventing `cert-manager` from seeing the correct certificate. After fixing that everything works fine.

Sorry for causing confusion and many thanks for you work!
