### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kashikoy** [aureq/cert-manager-webhook-ovh#46]
### What happened?

Hello,

I think there is a mistake.

From the webpage https://aureq.github.io/cert-manager-webhook-ovh :

Rights: (pre-populated)
GET /domaine/zone/*
PUT /domaine/zone/*
POST /domaine/zone/*
DELETE /domaine/zone/*

But it should be "domain" instead of “domaine”, shouldn't it ?

### Expected Behavior

I think it should be "domain".

### Steps to reproduce

I didn't try to use "domaine" because I already have an API key.

### Versions in use

0.6.0.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
@kashikoy yes, I think you're right. The perks of being French but coding in English. I'll get this fixed.

**Comment by kashikoy** [comment]
> @kashikoy yes, I think you're right. The perks of being French but coding in English. I'll get this fixed.

Bonjour Aurélien, j'aurais pu ouvrir ce ticket en français alors ! Merci beaucoup.
