### ISSUE TITLE
[breaking] TXT records are not allowed together with CNAME records (according to OVH)

### ISSUE THREAD

**Issue by hairyTomato** [aureq/cert-manager-webhook-ovh#47]
### What happened?

OVH DNS is missbehaving
- all domains have CNAME/TXT records according to webUI
- when querying the NS, I get a A record instead (which should be a CNAME record)
- sometimes I don't get a record at all, instead there is a SOA answer

### Expected Behavior

CNAME records being propagated properly

### Steps to reproduce

Have several Ingresses in the kubernetes cluster, we have about 7 of them.
Those Ingresses should have ovh-managed domains ofc

### Versions in use

ovh webhook - 0.6.0
cert manager - 1.12.7 (will be updated, but probably not related)
kubernetes - v1.29.3

### Additional context

According to OVH support:

> Dear client,
> 
> After reviewing your case, we observed that you have a TXT and CNAME record created for the same subdomain, and unfortunately, it is not possible to have both records for the same subdomain.
> 
> If you wish to propagate the CNAME record, it will be necessary to delete the TXT record.
> 
> There is no failure or error on the part of OVHcloud, but an incompatible configuration error when creating the records for the same subdomain.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hairyTomato** [comment]
> [2.4](https://www.rfc-editor.org/rfc/rfc1912#section-2.4) CNAME records
>    A CNAME record is not allowed to coexist with any other data.

**Comment by aureq** [comment]
@hairyTomato thanks for the report. I'm aware that you can't have other DNS records next to a CNAME.

However, you could please clarify your request? Looking at the code, the webhook doesn't create any CNAME.
And from what I read of your issue, I'm unsure of what you are requesting.

**Comment by hairyTomato** [comment]
@aureq we use this webhook and it created CNAME + TXT records for each Ingress according to OVH webinterface.

![grafik](https://github.com/aureq/cert-manager-webhook-ovh/assets/173990129/1b0a6cf1-41ae-4af8-9ef5-c97d57213b9c)

**Comment by hairyTomato** [comment]
I'll head back to OVH, I checked the webinterface, it shows CNAME records - but text format shows A records.

**Comment by hairyTomato** [comment]
I think I noticed that I opened the issue at the wrong repo.
Sorry for the inconvenience.

**Comment by hairyTomato** [comment]
Sidenote - externalDNS seems to create A + TXT records, which are fine.
But then there are "redirection" for exactly the same domains created.

While I check the dns records in text format, I don't see any CNAME records, but the webinterface from OVH show me no A records, instead only CNAME records for the problematic domains.
